<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ page import="com.dinevista.model.*,java.util.*" %>
<% request.setAttribute("pageTitle","Manage Event Booking"); request.setAttribute("activeNav","staffEventBookings"); EventBookingRecord b=(EventBookingRecord)request.getAttribute("booking"); List<EventPackageRecord> packages=(List<EventPackageRecord>)request.getAttribute("packages"); List<EventVenueRecord> venues=(List<EventVenueRecord>)request.getAttribute("venues"); String ctx=request.getContextPath(); %>
<%@ include file="fragments/header.jspf" %>
<section class="section-sm"><div class="container"><div class="section-heading"><div><span class="section-kicker">Event operations</span><h1>Update <%=b.getReference()%></h1></div></div>
<%List<String> errors=(List<String>)request.getAttribute("errors");if(errors!=null){%><div class="alert alert-error"><ul><%for(String e:errors){%><li><%=com.dinevista.util.HtmlUtil.escape(e)%></li><%}%></ul></div><%}%>
<div class="form-card"><form method="post" action="<%=ctx%>/staff/event-bookings/update"><input type="hidden" name="reference" value="<%=b.getReference()%>"><div class="form-grid">
<div class="form-group"><label>Contact name</label><input class="form-control" name="customerName" required value="<%=com.dinevista.util.HtmlUtil.escape(b.getCustomerName())%>"></div><div class="form-group"><label>Email</label><input class="form-control" name="email" type="email" required value="<%=com.dinevista.util.HtmlUtil.escape(b.getEmail())%>"></div>
<div class="form-group"><label>Phone</label><input class="form-control" name="phone" required value="<%=com.dinevista.util.HtmlUtil.escape(b.getPhone())%>"></div><div class="form-group"><label>Event type</label><input class="form-control" name="eventType" required value="<%=com.dinevista.util.HtmlUtil.escape(b.getEventType())%>"></div>
<div class="form-group"><label>Package</label><select class="form-control" name="packageId" required><%for(EventPackageRecord p:packages){%><option value="<%=p.getId()%>" <%=p.getId()==b.getPackageId()?"selected":""%>><%=com.dinevista.util.HtmlUtil.escape(p.getName())%></option><%}%></select></div>
<div class="form-group"><label>Venue</label><select class="form-control" name="venueId" required><%for(EventVenueRecord v:venues){%><option value="<%=v.getId()%>" <%=v.getId()==b.getVenueId()?"selected":""%>><%=com.dinevista.util.HtmlUtil.escape(v.getName())%></option><%}%></select></div>
<div class="form-group"><label>Date</label><input class="form-control" type="date" name="eventDate" required value="<%=b.getEventDate()%>"></div><div class="form-group"><label>Start time</label><input class="form-control" type="time" name="eventTime" required value="<%=b.getEventTime()%>"></div>
<div class="form-group"><label>Guests</label><input class="form-control" type="number" min="1" name="guestCount" required value="<%=b.getGuestCount()%>"></div><div class="form-group"><label>Status</label><select class="form-control" name="status"><%for(String st:Arrays.asList("INQUIRY","CONSULTATION","QUOTED","CONFIRMED","COMPLETED","CANCELLED")){%><option <%=st.equals(b.getStatus())?"selected":""%>><%=st%></option><%}%></select></div>
<div class="form-group full"><label>Notes / operational reason</label><textarea class="form-control" name="notes" maxlength="5000" rows="5"><%=com.dinevista.util.HtmlUtil.escape(b.getNotes())%></textarea></div>
</div><div class="form-actions"><button class="btn btn-primary" type="submit">Save booking</button><a class="btn btn-secondary" href="<%=ctx%>/staff/event-bookings/view?reference=<%=b.getReference()%>">Cancel</a></div></form></div></div></section><%@ include file="fragments/footer.jspf" %>
