<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ page import="com.dinevista.model.EventPackageRecord,java.util.*" %>
<% request.setAttribute("pageTitle","Event Package"); request.setAttribute("activeNav","staffEventPackages"); String mode=String.valueOf(request.getAttribute("packageFormMode")); EventPackageRecord p=(EventPackageRecord)request.getAttribute("eventPackage"); boolean edit="edit".equals(mode); String ctx=request.getContextPath(); %>
<%@ include file="fragments/header.jspf" %>
<section class="section-sm"><div class="container"><div class="section-heading"><div><span class="section-kicker">Event package</span><h1><%=edit?"Edit package":"Add package"%></h1></div></div>
<%List<String> errors=(List<String>)request.getAttribute("errors");if(errors!=null){%><div class="alert alert-error"><ul><%for(String e:errors){%><li><%=com.dinevista.util.HtmlUtil.escape(e)%></li><%}%></ul></div><%}%>
<div class="form-card"><form method="post" action="<%=ctx%>/staff/event-packages/<%=edit?"update":"create"%>"><%if(edit){%><input type="hidden" name="id" value="<%=p.getId()%>"><%}%><div class="form-grid">
<div class="form-group"><label>Package name</label><input class="form-control" name="name" required maxlength="140" value="<%=edit?com.dinevista.util.HtmlUtil.escape(p.getName()):String.valueOf(request.getAttribute("formName")==null?"":request.getAttribute("formName"))%>"></div>
<div class="form-group"><label>Category</label><select class="form-control" name="category" required><%for(String c:com.dinevista.service.EventPackageService.CATEGORIES){%><option <%=edit&&c.equals(p.getCategory())?"selected":""%> value="<%=c%>"><%=c%></option><%}%></select></div>
<div class="form-group"><label>Price per guest (LKR)</label><input class="form-control" type="number" step="0.01" min="0.01" name="price" required value="<%=edit?p.getPricePerGuest():String.valueOf(request.getAttribute("formPrice")==null?"":request.getAttribute("formPrice"))%>"></div>
<div class="form-group"><label>Minimum guests</label><input class="form-control" type="number" min="1" name="minimumGuests" required value="<%=edit?p.getMinimumGuests():String.valueOf(request.getAttribute("formMinimumGuests")==null?"10":request.getAttribute("formMinimumGuests"))%>"></div>
<div class="form-group"><label>Maximum guests</label><input class="form-control" type="number" min="1" name="maximumGuests" required value="<%=edit?p.getMaximumGuests():String.valueOf(request.getAttribute("formMaximumGuests")==null?"500":request.getAttribute("formMaximumGuests"))%>"></div>
<div class="form-group"><label>Duration (minutes)</label><input class="form-control" type="number" min="30" max="1440" name="durationMinutes" required value="<%=edit?p.getDurationMinutes():String.valueOf(request.getAttribute("formDurationMinutes")==null?"240":request.getAttribute("formDurationMinutes"))%>"></div>
<div class="form-group full"><label>Description</label><textarea class="form-control" name="description" maxlength="800" rows="4"><%=edit?com.dinevista.util.HtmlUtil.escape(p.getDescription()):String.valueOf(request.getAttribute("formDescription")==null?"":request.getAttribute("formDescription"))%></textarea></div>
<div class="form-group full"><label>Inclusions, comma-separated</label><textarea class="form-control" name="inclusions" maxlength="5000" rows="4"><%=edit?com.dinevista.util.HtmlUtil.escape(p.getInclusions()):String.valueOf(request.getAttribute("formInclusions")==null?"":request.getAttribute("formInclusions"))%></textarea></div>
<%if(edit){%><div class="form-group"><label><input type="checkbox" name="active" value="true" <%=p.isActive()?"checked":""%>> Active package</label></div><%}%>
</div><div class="form-actions"><button class="btn btn-primary" type="submit"><%=edit?"Save changes":"Create package"%></button><a class="btn btn-secondary" href="<%=ctx%>/staff/event-packages">Cancel</a></div></form></div></div></section>
<%@ include file="fragments/footer.jspf" %>
